/* DKU Tarot - Major Arcana Data */
const MAJOR_ARCANA = [
  {
    id: 0,
    numeral: '0',
    name: 'The Fool',
    keywords: 'New beginnings, spontaneity, innocence',
    meaning: 'A fresh start awaits. Embrace the unknown with an open heart and trust the journey ahead.',
    icon: 'explore',
  },
  {
    id: 1,
    numeral: 'I',
    name: 'The Magician',
    keywords: 'Willpower, skill, resourcefulness',
    meaning: 'You have all the tools you need. Channel your focus and manifest your intentions into reality.',
    icon: 'auto_fix_high',
  },
  {
    id: 2,
    numeral: 'II',
    name: 'The High Priestess',
    keywords: 'Intuition, mystery, inner wisdom',
    meaning: 'Trust your inner voice. The answers you seek lie within, beyond the surface of things.',
    icon: 'visibility',
  },
  {
    id: 3,
    numeral: 'III',
    name: 'The Empress',
    keywords: 'Abundance, nurture, creativity',
    meaning: 'A time of growth and creative abundance. Nurture your ideas and let them blossom naturally.',
    icon: 'local_florist',
  },
  {
    id: 4,
    numeral: 'IV',
    name: 'The Emperor',
    keywords: 'Authority, structure, stability',
    meaning: 'Build solid foundations. Take charge with discipline and bring order to your plans.',
    icon: 'shield',
  },
  {
    id: 5,
    numeral: 'V',
    name: 'The Hierophant',
    keywords: 'Tradition, guidance, education',
    meaning: 'Seek wisdom from mentors and established knowledge. Learning from tradition brings clarity.',
    icon: 'school',
  },
  {
    id: 6,
    numeral: 'VI',
    name: 'The Lovers',
    keywords: 'Love, harmony, choices',
    meaning: 'A significant choice stands before you. Follow your heart and align with your deepest values.',
    icon: 'favorite',
  },
  {
    id: 7,
    numeral: 'VII',
    name: 'The Chariot',
    keywords: 'Determination, willpower, victory',
    meaning: 'Move forward with confidence and determination. Victory comes through focused will.',
    icon: 'directions_car',
  },
  {
    id: 8,
    numeral: 'VIII',
    name: 'Strength',
    keywords: 'Courage, patience, inner strength',
    meaning: 'True strength comes from within. Face challenges with gentle courage and quiet resilience.',
    icon: 'fitness_center',
  },
  {
    id: 9,
    numeral: 'IX',
    name: 'The Hermit',
    keywords: 'Solitude, reflection, inner guidance',
    meaning: 'Take time for solitude and reflection. The light of wisdom shines brightest in stillness.',
    icon: 'nights_stay',
  },
  {
    id: 10,
    numeral: 'X',
    name: 'Wheel of Fortune',
    keywords: 'Cycles, destiny, turning points',
    meaning: 'The wheel turns. Change is natural and inevitable — embrace the new cycle beginning now.',
    icon: 'autorenew',
  },
  {
    id: 11,
    numeral: 'XI',
    name: 'Justice',
    keywords: 'Fairness, truth, accountability',
    meaning: 'Seek truth and act with integrity. Fair outcomes arise from honest actions.',
    icon: 'balance',
  },
  {
    id: 12,
    numeral: 'XII',
    name: 'The Hanged Man',
    keywords: 'Pause, surrender, new perspective',
    meaning: 'Let go of control and see things from a new angle. Patience reveals hidden wisdom.',
    icon: 'pause_circle',
  },
  {
    id: 13,
    numeral: 'XIII',
    name: 'Death',
    keywords: 'Transformation, endings, renewal',
    meaning: 'An old chapter closes so a new one can begin. Embrace transformation with grace.',
    icon: 'transform',
  },
  {
    id: 14,
    numeral: 'XIV',
    name: 'Temperance',
    keywords: 'Balance, moderation, patience',
    meaning: 'Find your center through balance and patience. Harmony comes from blending opposites.',
    icon: 'water_drop',
  },
  {
    id: 15,
    numeral: 'XV',
    name: 'The Devil',
    keywords: 'Attachment, shadow, materialism',
    meaning: 'Examine what binds you. Awareness of your chains is the first step to freedom.',
    icon: 'link',
  },
  {
    id: 16,
    numeral: 'XVI',
    name: 'The Tower',
    keywords: 'Upheaval, revelation, breakthrough',
    meaning: 'Sudden change breaks down old structures. From the rubble, truth and freedom emerge.',
    icon: 'flash_on',
  },
  {
    id: 17,
    numeral: 'XVII',
    name: 'The Star',
    keywords: 'Hope, inspiration, serenity',
    meaning: 'Hope shines after the storm. Trust in renewal and let your spirit be replenished.',
    icon: 'star',
  },
  {
    id: 18,
    numeral: 'XVIII',
    name: 'The Moon',
    keywords: 'Illusion, intuition, the unconscious',
    meaning: 'Not everything is as it seems. Navigate uncertainty by trusting your deepest intuition.',
    icon: 'dark_mode',
  },
  {
    id: 19,
    numeral: 'XIX',
    name: 'The Sun',
    keywords: 'Joy, vitality, success',
    meaning: 'Warmth and clarity surround you. Celebrate life and let your true self shine brightly.',
    icon: 'wb_sunny',
  },
  {
    id: 20,
    numeral: 'XX',
    name: 'Judgement',
    keywords: 'Rebirth, calling, reckoning',
    meaning: 'Answer your inner calling. A moment of awakening brings clarity about your true path.',
    icon: 'campaign',
  },
  {
    id: 21,
    numeral: 'XXI',
    name: 'The World',
    keywords: 'Completion, fulfillment, wholeness',
    meaning: 'A cycle reaches completion. Celebrate your achievements and prepare for what comes next.',
    icon: 'public',
  },
];
